# Generated by Django 2.1.7 on 2020-05-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.TextField(blank=True, default='placeholder', null=True)),
                ('Name', models.TextField(blank=True, default='placeholder', null=True)),
                ('IataCode', models.TextField(blank=True, default='placeholder', null=True)),
                ('IcaoCode', models.TextField(blank=True, default='placeholder', null=True)),
                ('CountryName', models.TextField(blank=True, default='placeholder', null=True)),
                ('CountryCode', models.TextField(blank=True, default='placeholder', null=True)),
                ('CityCode', models.TextField(blank=True, default='placeholder', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=2)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test', models.TextField()),
            ],
        ),
    ]
