# Generated by Django 2.1.7 on 2019-09-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0003_countrymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='countrymodel',
            old_name='name',
            new_name='Name',
        ),
    ]
