# Generated by Django 2.1.7 on 2019-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0005_remove_airportmodel_delayindexurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportmodel',
            name='CityCode',
            field=models.TextField(default='CityCode'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='CountryCode',
            field=models.TextField(default='CountryCode'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='CountryName',
            field=models.TextField(default='CountryName'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='IataCode',
            field=models.TextField(default='IataCode'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='IcaoCode',
            field=models.TextField(default='IcaoCode'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='Id',
            field=models.TextField(default='Id'),
        ),
        migrations.AddField(
            model_name='airportmodel',
            name='Name',
            field=models.TextField(default='Name'),
        ),
    ]
