# Generated by Django 2.1.7 on 2019-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0006_auto_20191128_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportmodel',
            name='CityCode',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='CountryCode',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='CountryName',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='IataCode',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='IcaoCode',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='Id',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='Name',
            field=models.TextField(default='placeholder'),
        ),
    ]
