# Generated by Django 2.1.7 on 2019-11-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0007_auto_20191128_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirportModel',
        ),
    ]
