# Generated by Django 2.1.7 on 2019-11-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0009_airportmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirportModel',
        ),
    ]
