# Generated by Django 2.1.7 on 2020-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0010_delete_airportmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.TextField(default='placeholder')),
                ('Name', models.TextField(default='placeholder')),
                ('IataCode', models.TextField(default='placeholder')),
                ('IcaoCode', models.TextField(default='placeholder')),
                ('CountryName', models.TextField(default='placeholder')),
                ('CountryCode', models.TextField(default='placeholder')),
                ('CityCode', models.TextField(default='placeholder')),
            ],
        ),
    ]
