# Generated by Django 2.1.7 on 2020-04-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_trackr_app', '0011_airportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportmodel',
            name='CityCode',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='CountryCode',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='CountryName',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='IataCode',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='IcaoCode',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='Id',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='Name',
            field=models.TextField(blank=True, default='placeholder', null=True),
        ),
    ]
